- name: chef
  box: "bento/ubuntu-14.04"
  hostname: local.chef.com
  ip: 10.10.10.101
  cpus: 2
  memory: 1024
  mount:
    - source: ../
      destination: /global
      id: chef-server
  provision: provision/box.sh
  group: chef-server
